// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmuovgfxujfpbcelppke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtdW92Z2Z4dWpmcGJjZWxwcGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDM3MDUsImV4cCI6MjA2NjUxOTcwNX0.i32jMEmjkh6GiA4k8eBZZhvNDNklFWx2UXHGJih9u5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);